"""SQLite persistence: content cache, card state, and the append-only review log."""

from .cards import (
    CardState,
    all_states,
    card_ids,
    declare_known,
    declared_count,
    distractor_counts,
    distractors_for,
    get_state,
    save_state,
    sync,
    undo_known,
)
from .db import connect, session
from .reports import (
    REASONS,
    Report,
    Snapshot,
    all_reports,
    last_answer,
    open_report_count,
    open_reports,
    report_card,
    resolve_report,
    withdraw_report,
)
from .reviews import (
    count_on,
    first_seen_on,
    lesson_first_seen_on,
    recent_ratings,
    recent_ratings_for,
    record_answer,
)

__all__ = [
    "REASONS",
    "CardState",
    "Report",
    "Snapshot",
    "all_reports",
    "all_states",
    "card_ids",
    "connect",
    "count_on",
    "declare_known",
    "declared_count",
    "distractor_counts",
    "distractors_for",
    "first_seen_on",
    "get_state",
    "last_answer",
    "lesson_first_seen_on",
    "open_report_count",
    "open_reports",
    "recent_ratings",
    "recent_ratings_for",
    "record_answer",
    "report_card",
    "resolve_report",
    "save_state",
    "session",
    "sync",
    "undo_known",
    "withdraw_report",
]
